secure: "W+ZjOrHuSKMX2lM7zWgdZkeSqKQ3uUVapPitbBznSbtbMffA6pdTxONL7ktYYiJQxzkDcTQYafBbiYmF4PCVSbmrgl/ybrDBDVlr0ZgOGCCGH1zobG4kpa5OvLFoWA5Sf48e9zXRQljo+xKFgs3ZFvecRkYp0uJgNB7bjJiiAvax8eJ+h+tQsoz2e3nConvss4xIeTCPOCiS1BXodeJ3grP4xfQs7BfI8wlD9/nyGIDqV4nD0Slradya00vxniuozwbuAw5tGeasvTU6Q5kF0w509x2ovJRtAl07gf64uGle/YXItfbCm6wyFfPMPeQUnYSLylaDH5nKrYRO7F3PZ70BEKrXg5du3ys9kPMxQ3eNYjRbNH1vy215ESw9e4DWHLmzoZvBUMIWcXtCd5KVzH96BnRSfpxUYZyR3/g7LWPO/FdCD0xnVqaHNN3Iz1GXsIOEmLELoya+HZ7EvTcku9hCHgmHJFrHalxRSflwS1A3ipqd/JC+U5Q/5J9/FTKdNmQIBK2MZhWywCZOxu11smFDmBAX7aMhNj5LYgaqAD9qTNQgdxjIKjzOsesLl2gzdIJpBoncTGEIolRoyU1PlGGRy8rF+N6XH8h5PB1Fae4HpfiYq+O1+YKMwQrGe/ZUxRt5isihAn+U2M+r3bfN/ZOc783j1jthdeZR3I4EefM="

language: node_js
node_js:
  - lts/*

branches:
  only:
    - master
    - beta
 
deploy:
  provider: npm
  email: "alex.jared.moon@gmail.com"
  api_key: "GXDyriSOe/SdtfQ2sHNT3a3RzEfvsWCIbfBUElB6dLP7N+ID7ABReicoyCLFuKoS0eU6v0CCNEQrDypE13lJ6k3fz+WU4nCFQ0qFZOhjZ9TE0Doiz3154D6rWazxJ92Ps7xF9ah3GrGq0xn3OLXViK4M3Z2xuG6gamE/X6ghDxQ0ph9VYfStCv6JTmGdtxfpk9kbIFQR7OWEFWmZYKD874RRuOZgnY+7pEmAoii1HvKU+tMK3vaKm+OarnKh+8E2UXCVJpHnvgu3qnkjUFlhdoOyEw69alNzKIZuR10wtXOPCilbmTm8mfiAIRN34jbUp52lMOZG84vhc7W3+h7zmw4VfXteqgsSkzUXBReoufeSjqajHiXDSa3ZTxEOo+FURy79CbviQjprVILYeDRyEpKFmY1+2UfnBC0JS7muDQSugbjxf+lpZGEiu6x67qJ5WH0ammEo0FLg6aZJMDylaKd9Z1PYJI/HqPrtkmpCFnCZUjjxWjaRdhZTERkoImb4bSbvzKOH89fp6x7JFZXU7ljYRepVsjavTRD/pooAmgUqrpU8GNdkYtET8XeJyYoJjry3OwfqgB6m+MRgb94UAVC5j7NBu5t9X+PsFPh5RSFgNivkRneNaD46YwPjoLGKYNTYUsQXGLropVxCtNg0g8xt3+6l80WQhyU1fK8oXRI="
  on:
    tags: true
    branch: master
  skip_cleanup: true